version: 2
updates:
- package-ecosystem: gomod
  directory: "/helper-utility"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.37.1
- package-ecosystem: gomod
  directory: "/ecr-scanner"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.37.1
    - 1.37.20
